<?php if ($error != "") { 
		?>
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<p class="bg-danger"><?php echo $error; ?></p>
				</div>
			</div>
		</div><?php
	}
?>
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<form action="register.php" method="post" role="form">
				<div class="form-group">
					<label for="username">Username</label>
					<input type="text" class="form-control" name="username" value="<?php echo $username; ?>">
				</div>
				<div class="form-group">
					<label for="password">Password</label>
					<input type="password" class="form-control" name="password" value="<?php echo $password; ?>">
				</div>
				<div class="form-group">
					<label for="password-confirm">Confirm Pasword</label>
					<input type="password" class="form-control" name="password-confirm" value="<?php echo $password_confirm; ?>">
				</div>
				<div class="form-group">
					<label for="email">E-mail</label>
					<input type="email" class="form-control" name="email" value="<?php echo $email; ?>">
				</div>
				<a href="index.php" class="btn btn-secondary">Back</a>
				<button type="submit" class="btn btn-primary" name="submit-form">Register</button>
			</form>
		</div>
	</div>
</div>