<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<div class="jumbotron">
				<h1>Hello, <?php echo $user->username; ?>!</h1>
				<p>You've been registered and logged in.</p>
				<p><a class="btn btn-primary btn-lg" role="button" href="index.php">Home Page</a></p>
				<p><a class="btn btn-primary btn-lg" role="button" href="logout.php">Logout</a></p>
			</div>
		</div>
	</div>
</div>
